version: '3'

services:
  grafana:
    container_name: "k6_grafana"
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - net

  influxdb:
    container_name: "k6_influxdb"
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - net
  
  chronograf:
    container_name: "k6_chronograf"
    image: chronograf:alpine
    ports:
      - 8888:8888
    volumes:
      - chronograf:/var/lib/chronograf
    networks:
      - net
    command: "--influxdb-url=http://k6_influxdb:8086"

  k6:
    container_name: "k6_script"
    image: loadimpact/k6
    depends_on:
      - influxdb
      - grafana
    volumes:
      - ./:/test
    networks:
      - net
    command: "run --out influxdb=http://k6_influxdb:8086/myk6db /test/script_scenario_ramping_arrival_rate.js"


volumes:
  influxdb:
  chronograf:

networks:
  net: